# Generated by Django 5.1.4 on 2025-01-12 11:40

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ShortLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_url", models.CharField(max_length=512)),
                ("passcode", models.CharField(blank=True, default="", max_length=64)),
                ("salt", models.CharField(blank=True, default="", max_length=64)),
                ("redirect_string", models.CharField(max_length=8)),
            ],
        ),
    ]
