# Generated by Django 5.1.4 on 2025-01-12 17:24

import yaus.shortener.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("yaus", "0004_alter_shortlink_redirect_string"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shortlink",
            name="redirect_string",
            field=models.CharField(
                default=yaus.shortener.utils.Utils.generate_redirect_string,
                max_length=64,
                unique=True,
            ),
        ),
    ]
